location /health {
    access_log off;
    return 200 '{"status":"UP","service":"ui"}';
    add_header Content-Type application/json;
}

location /api/ {
    client_max_body_size 20m;
    proxy_pass http://${BFF_HOST}/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location / {
    try_files $uri $uri/ /index.html;
}
