apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ips-viewer
  labels:
    app.kubernetes.io/name: ips-viewer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: smart-app
    app.kubernetes.io/part-of: cpg-to-acp
spec:
  replicas: {{ .Values.ipsViewer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ips-viewer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ips-viewer
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: smart-app
        app.kubernetes.io/part-of: cpg-to-acp
    spec:
      containers:
        - name: ips-viewer
          image: {{ .Values.image.registry }}/{{ .Values.image.namespace }}/{{ .Values.ipsViewer.image.name }}:{{ .Values.ipsViewer.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.ipsViewer.port }}
          resources:
            {{- toYaml .Values.ipsViewer.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ipsViewer.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ipsViewer.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
