apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-ips-viewer
  labels:
    app.kubernetes.io/name: ips-viewer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: smart-app
    app.kubernetes.io/part-of: cpg-to-acp
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-ips-viewer
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
