apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mock-ehr-app
  labels:
    app.kubernetes.io/name: mock-ehr-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ehr-ui
    app.kubernetes.io/part-of: cpg-to-acp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mockEhrApp.service.port }}
      targetPort: {{ .Values.mockEhrApp.port }}
      name: http
  selector:
    app.kubernetes.io/name: mock-ehr-app
    app.kubernetes.io/instance: {{ .Release.Name }}
