image:
  registry: quay.io
  namespace: cpgtoacp
  name: litellm
  tag: latest

replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  port: 4000

openai:
  apiKey: ""

litellm:
  masterKey: ""
