image:
  registry: image-registry.openshift-image-registry.svc:5000
  # Namespace is overridden by deploy scripts (--set image.namespace=...)
  namespace: default
  name: decision-service
  tag: latest

replicas: 1

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

service:
  port: 8081
